# Generated by Django 5.1.1 on 2024-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manager', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='topic_id',
            field=models.CharField(default='-1001234567890', max_length=255),
        ),
    ]
