# Generated by Django 5.1.3 on 2024-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manager', '0003_post_pinned_post_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic_id',
            field=models.CharField(max_length=255),
        ),
    ]
